# Generated by Django 5.1.1 on 2024-10-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.ImageField(upload_to='')),
                ('discounted_price', models.IntegerField()),
                ('brand', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('product_image', models.ImageField(upload_to='product_images')),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Clothing', 'Clothing'), ('Books', 'Books'), ('Home & Garden', 'Home & Garden'), ('Sports & Outdoors', 'Sports & Outdoors'), ('Health & Beauty', 'Health & Beauty'), ('Kids & Baby', 'Kids & Baby'), ('Other', 'Other')], max_length=100)),
            ],
        ),
    ]
