# Generated by Django 5.1.1 on 2024-10-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_alter_product_selling_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Honey', 'Honey'), ('Nuts', 'Nuts'), ('Flour', 'Flour'), ('Spices', 'Spices'), ('Tea', 'Tea'), ('Vinegar', 'Vinegar'), ('Health Supplements', 'Health Supplements'), ('Dates', 'Dates'), ('Monthly Packs', 'Monthly Packs'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='discounted_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
