# Generated by Django 5.1.1 on 2024-10-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_alter_product_brand_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Honey', 'Honey'), ('oil', 'oil'), ('Flour', 'Flour'), ('Spices', 'Spices'), ('Tea', 'Tea'), ('Vinegar', 'Vinegar'), ('Health Supplements', 'Health Supplements'), ('Dates', 'Dates'), ('Monthly Packs', 'Monthly Packs'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.CharField(max_length=100),
        ),
    ]
